### ISSUE TITLE
Where the code of the hook?

### ISSUE THREAD

**Issue by ajaymathur** [kevinwolfcr/formal#2]
Hey, I want to look at the implementation of the hook but I cannot find the code.

In the hook file https://github.com/kevinwolfcr/formal/blob/master/src/use-formal.ts#L1 I see:

```
export default function useFormal(): void {}
```

Maybe the code is not pushed yet? 🙂 ❤️

**Comment by kevinwolfcr** [comment]
Hi @ajaymathur, thanks for reaching out. Yeah haha it is my bad. Actually, I started yesterday but I took the approach of first writing the README and then code the actual implementation 😅

I expect to be releasing it before the weekend, maybe the first (really basic) version tonight.
