### ISSUE TITLE
getFieldProps() could yield a "required" property as specified in yup schema

### ISSUE THREAD

**Issue by dotlouis** [kevinwolfcr/formal#27]
I have defined a Yup schema like so:
```JS
const schema = yup.object().shape({
  firstName: yup.string().required()
})
```
I would expect that the `formal.getFieldProps('firstName')` to return a `required` property so I can write `<input {...formal.getFieldProps('firstName')}/>` without having to re-specify the required attribute.

What do you think?

**EDIT**: ok I just figured out that we may not want to do this because the default browser validation takes over and displays its own validation message, preventing the JS validation.

![Screenshot 2019-04-09 at 14 30 09](https://user-images.githubusercontent.com/1891109/55800463-185faa00-5ad4-11e9-804b-e972af66097f.png)

What I plan to do is to dynamically add a `<form noValidate>`attribute to prevent default field validation when JS is enabled (via `useEffect`). Thus giving the brower the ability to still perform basic validation if, for some reason, JS is disabled.

**Comment by kevinwolfcr** [comment]
tbh, I think this should be out of the user choice, my goal with this library it's to provide just the primitives needed to work.

**Comment by dotlouis** [comment]
After having thought about it, it seems logical to me.
In fact, right now, the required attribute is opt-in while otherwise, it would be opt-out and having to force a required to false would be nasty.
