### ISSUE TITLE
RFC: Support other validation methods than Yup

### ISSUE THREAD

**Issue by dotlouis** [kevinwolfcr/formal#28]
Hello,
First of all, thanks for working on this package! 😃 
Rather than working on my own internal version of a hook-powered form lib, I thought I may help with this one.

My first question when I got into the decision to use a library to handle form validation was, of course, which one?
It came down to two choices:
- a library of helpers that takes care of inputs handlers and flags such as formal
- a library that handles schema validation such as Yup.

I went with Yup as the default lib used by formal. I'm fine with it for now but I'd like to know if someone found out the cost of adding such a package to their web page [(75.3Kb minified)](https://bundlephobia.com/result?p=yup@0.27.0). And if other lighter solutions are studied. I'm thinking of something like [superstruct](https://github.com/ianstormtaylor/superstruct) which weights [5.8x less](https://bundlephobia.com/result?p=superstruct@0.6.1).

Regardless of the weight argument, one may want to use their own validation logic. Could it be feasible to open formal to other validation methods?
What do you think?

**Comment by kevinwolfcr** [comment]
For now, I am happy with just Yup, since is kind of the most used. But I am happy to try to support other ones. The thing is that if we assume the user is always using Yup, we can have more control over the individual fields validation, because we can now if the schema is async or not.

**Comment by dotlouis** [comment]
Thanks for your answer, I understand, and I'm totally fine with Yup for the time being. But I think that to provide a simple hook (as in 'callback' not 'react hook') would be a powerful addition to allow everyone to plugin their custom validation logic if they don't use Yup. Maybe a reflexion for a later stage. For now, I agree that it would slow down development.

**Comment by indiejoseph** [comment]
Just stumbled upon this, I think Yup is a very good and popular validator, but please consider decoupling the validation handling and here I have few suggestions:

1.) Add callback `formal.onValidate` instead of calling `schemaHasAsyncValidation`
2.) Having isDirty in field level `formal.getFieldProps`(This is not related to this topic)

**Comment by steffenmllr** [comment]
I second what @indiejoseph is saying. 75.3Kb or 21.6kb gzipped is 7 times the size of my view library (preact). a simple callback to roll my own would be appreciated.

**Comment by adjourn** [comment]
If this is a deal-breaker for someone (like myself), there's also [this](https://github.com/wsmd/react-use-form-state).
