### ISSUE TITLE
Support for translation/internationalization of error messages?

### ISSUE THREAD

**Issue by danawoodman** [kevinwolfcr/formal#31]
## The problem

My app supports English and Japanese (Using react-i18next btw) and I need to translate error messages into Japanese.

## The solution

If possible, error messages could be translated using some sort of key that could be used to lookup the translation and use that instead. 

## Notes

I'm using react-i18next but whatever solution should support any translation/internationalization library.

**Comment by kevinwolfcr** [comment]
Hi, @danawoodman. For the translation messages you can reference https://github.com/jquense/yup API. You can put the translation key as the yup error message and then use whatever you want to transform that error.

Here is an example:
https://codesandbox.io/s/321mxprwp

Did it helped?
