### ISSUE TITLE
formal.change only update last field if they called sequentially

### ISSUE THREAD

**Issue by himselfego** [kevinwolfcr/formal#41]
# Bug

formal.change only update last field if they called sequentially. I don't really if this is happening in useEffect hook only. 

## Reproduction steps

1. Make form with 2 fields
2. In useEffect after prop change update 2 field sequentially

Here is sandbox with this issue: https://codesandbox.io/s/jznpxm32z5

**Comment by himselfego** [comment]
Oh. Sorry, saw that you already closed similar issue.

**Comment by ifndefdeadmau5** [comment]
@kevinwolfcr 
I'm also having the same issue.
But looks like fix PR has been merged?  (https://github.com/kevinwolfcr/formal/pull/34) So I'm wondering if new release hasn't been come out yet or something
