### ISSUE TITLE
Crash with missing schema when not using default name

### ISSUE THREAD

**Issue by winkelsdorf** [kevinwolfcr/formal#49]
# Bug

I am trying to create a multistep form using different `schemes` and `initialValues` for each step. When trying to move the initialValues and schemes out of the related arrow functions, I noticed that `formal.validate()` always crashes as soon as the schema is renamed.

## Reproduction steps

Create a form like mentioned in the docs. Call it schema2 instead of schema `const schema2 = yup.object().shape(..)` and then call `useFormal` with that schema.

Upon validation the crash occurs.

```js
const formal = useFormal(initialValues, {
    schema2, // crashes
    onSubmit: values => onSubmit(values),
  });
```

I am trying to prepare an expo now.

## Suggested solution

As soon as the schema and the function call are using `schema` as variable name it's working fine.

## Notes

Using React-Native 
```shell
react-native-cli: 2.0.1
react-native: 0.59.8
@kevinwolf/formal-native@^0.1.0
@kevinwolf/formal@^0.1.0
```

## Screenshot

<img width="524" alt="Screen Shot 2019-05-28 at 19 16 29" src="https://user-images.githubusercontent.com/1413291/58498346-264db500-817e-11e9-8dd2-1e7c72651a00.png">

**Comment by winkelsdorf** [comment]
I'm unable to provide a working snack for expo as it looks like hooks are not yet supported on their end:

`Device: (3:4205) TypeError: i.useState is not a function. (In 'i.useState(e)', 'i.useState' is undefined)`.

**Comment by adjourn** [comment]
Of course it crashes, it's a shorthand for:
```js
const formal = useFormal(initialValues, {
  schema2: schema2, // crashes
  onSubmit: values => onSubmit(values),
});
```

If you want to use different name:
```js
const formal = useFormal(initialValues, {
  schema: schema2, // doesn't crash
  onSubmit: values => onSubmit(values),
});
```

**Comment by winkelsdorf** [comment]
Yikes! What a mistake, totally overlooked the shorthand syntax here  👀 

Thank you very much @adjourn!

**Comment by adjourn** [comment]
Don't feel too bad, we all have those days.

**Comment by winkelsdorf** [comment]
Absolutely, thankfully you were able to help so quickly!
